# Generated by Django 2.0.9 on 2020-12-06 20:23

from django.db import migrations, models
import handwritten.signatures.models.signatures


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=handwritten.signatures.models.signatures.directory_path)),
            ],
        ),
    ]
