# Generated by Django 2.2 on 2020-12-11 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import handwritten.verifications.models.verifications


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Date time was modified', verbose_name='modified at')),
                ('validation_range', models.FloatField(null=True)),
                ('picture', models.ImageField(upload_to=handwritten.verifications.models.verifications.directory_path)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
